services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:      


